name: Convert Video to MP3

on:
  workflow_dispatch:
    inputs:
      video_url:
        description: 'URL of the video to convert (YouTube URL)'
        required: true

jobs:
  convert_to_mp3:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y ffmpeg
          sudo apt install -y python3-pip
          pip3 install yt-dlp

      - name: Save Cookies
        run: |
          echo "VISITOR_INFO1_LIVE=hqzTKY0SfWg; VISITOR_PRIVACY_METADATA=CgJTRxIEGgAgWw%3D%3D; PREF=tz=Asia.Shanghai&f5=30000&f7=150; LOGIN_INFO=AFmmF2swRAIgU8IetdO7pYDbo19TAcCKepaCgNGed_KwtuY2-MVLNtYCIB7nkksNmX53tmIDiWyVDPrcHMkwzdVwi3WLircf_wTT:QUQ3MjNmeW91UzFpOUlKUnprOGhXR2lBcG90Ny1Pcm43Z0d3SVBtSEF5OEcwaGZiNXBFbXRscHM3UHBrbTZWOVFYUTB3QUdPNXpFU1F1STlLMmNQX0R5YUJCTjVQdlBhOHNhZWVlc1U0MWdpQnVwZzZaZHcxWVhEOHNYWHRpaUoyN1BJa3A1dFdSVkVxUEFSZXJudHBUVnlYQmFzMnNxMlhR; SIDCC=AKEyXzVzbV9AIY8gtjxqzXiKzkLuxWyM9ODLzQInLZXm3vNbA7gIJQZOM6809lk6KIu5EKx2mjo; __Secure-1PSIDCC=AKEyXzXoPtkiDBRBq2wwZr07u5_0m25-DjIgyXts3c0YBUZM9N0j_cSWvcLBGXCnbAHUdnJt298; __Secure-3PSIDCC=AKEyXzWUmBxTc1769Y1ZR1CioxuNwQpw4M9O51Z0hdYbZhTI5szBPZORSWSCsWbUh7-zhhGjSw; HSID=AT5mCyEQiRcKeaQF3; SSID=AvV0KgZfBXw0_mNVP; APISID=8mz6r5Jti40ybrXk/Aw_cCiMMd7wi8sWid; SAPISID=GmUlwJ8uROZFeufo/AGAiAB39gc2l1DnyE; __Secure-1PAPISID=GmUlwJ8uROZFeufo/AGAiAB39gc2l1DnyE; __Secure-3PAPISID=GmUlwJ8uROZFeufo/AGAiAB39gc2l1DnyE; SID=g.a000pQjZ3NhAn8ugP1Z47xCpYIly6WrHHBeTD8g2F7Q79wDBvFoMpEg9V63dZFAFXwrZNxC8dwACgYKASASARISFQHGX2MioGcHNG66TvwsuZlNcXWn2BoVAUF8yKoXQ-d3qPn4KOPph7vcYPHf0076; __Secure-1PSID=g.a000pQjZ3NhAn8ugP1Z47xCpYIly6WrHHBeTD8g2F7Q79wDBvFoMplC76r46lGkGeo2kWOHemAACgYKARgSARISFQHGX2MiK5HEmRfH7P6rPc1L1PJMThoVAUF8yKreLKE6iOy8AL0AzQ56MUvf0076; __Secure-3PSID=g.a000pQjZ3NhAn8ugP1Z47xCpYIly6WrHHBeTD8g2F7Q79wDBvFoM6Pu9aQEWOVaybq8wb1fczQACgYKASUSARISFQHGX2Mit-aloyJjH4GAcZEN0VbozxoVAUF8yKpctY_Wj5dX__zoziwlvfF40076; YSC=Kev9WpVDfEI; __Secure-1PSIDTS=sidts-CjEBQT4rX8RGFIZGnTwgPmxTTgq8L8fZteRyIbyvFvbd1mHxdc8v0H1na7NZcP26czSyEAA; __Secure-3PSIDTS=sidts-CjEBQT4rX8RGFIZGnTwgPmxTTgq8L8fZteRyIbyvFvbd1mHxdc8v0H1na7NZcP26czSyEAA" > cookies.txt

      - name: Download Video File
        run: |
          yt-dlp --cookies cookies.txt -f bestvideo+bestaudio/best -o input_video.mp4 "${{ github.event.inputs.video_url }}"

      - name: Convert Video to MP3
        run: |
          ffmpeg -i input_video.mp4 -q:a 0 -map a output_audio.mp3

      - name: Create Release
        uses: actions/create-release@v1
        with:
          tag_name: "audio-${{ github.run_id }}"
          release_name: "Converted Audio"
          draft: false
          prerelease: false

      - name: Upload MP3 to Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: output_audio.mp3
          asset_name: output_audio.mp3
          asset_content_type: audio/mpeg

      - name: Output Release URL
        run: echo "::set-output name=url::${{ steps.create_release.outputs.upload_url }}"
