name: Convert Video to MP3

on:
  workflow_dispatch:
    inputs:
      video_url:
        description: 'URL of the video to convert (YouTube URL)'
        required: true

jobs:
  convert_to_mp3:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y ffmpeg
          sudo apt install -y python3-pip
          pip3 install yt-dlp

      - name: Save Cookies
        run: echo "${{ secrets.YOUTUBE_COOKIES }}" > cookies.txt

      - name: Download Video File
        run: |
          yt-dlp --cookies cookies.txt -f bestvideo+bestaudio/best -o input_video.mp4 "${{ github.event.inputs.video_url }}"
        continue-on-error: false  # 如果下载失败，终止工作流

      - name: Convert Video to MP3
        run: |
          ffmpeg -i input_video.mp4 -q:a 0 -map a output_audio.mp3
        continue-on-error: false  # 如果转换失败，终止工作流

      - name: Create Release
        uses: actions/create-release@v1
        with:
          tag_name: "audio-${{ github.run_id }}"
          release_name: "Converted Audio"
          draft: false
          prerelease: false

      - name: Upload MP3 to Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: output_audio.mp3
          asset_name: output_audio.mp3
          asset_content_type: audio/mpeg

      - name: Cleanup
        run: |
          rm -f input_video.mp4 output_audio.mp3 cookies.txt

      - name: Output Release URL
        run: echo "::set-output name=url::${{ steps.create_release.outputs.upload_url }}"
